.TH xdg-xmenu 1 "September 2021" git
.SH NAME
xdg-xmenu - generate desktop menu file for
.IR xmenu (1)
.SH SYNOPSIS
xdg\-xmenu
[\fB\-a\fR]
[\fB\-b \fIfallback_font\fR]
[\fB\-f\fR]
[\fB\-i \fIicon_theme\fR]
[\fB\-n\fR]
[\fB\-s \fIicon_size\fR]
[\fB\-S\fR]
[\fB\-t \fIterminal\fR]
.SH DESCRIPTION
xdg-xmenu is a shell script to generate an XDG desktop menu file for xmenu.
.SH OPTIONS
.TP
\fB\-a\fR
Show icons with 'OnlyShowIn' key in .desktop file.
These desktop entries are usually programs specifically for desktop environments.
Default is not showing those desktop entries.
.TP
\fB\-b \fIfallback_icon\fR
Fallback icon in case one can not be found.
Both an icon name and a file path is acceptable.
Default is application-x-executable.
.TP
\fB\-f\fR
Force to cache svg icons to png, even if cached images already exist. Useful
when switching to a new icon theme.
.TP
\fB\-i \fIicon_theme\fR
Icon theme. Default is parsed from gtk3 configuration file.
.TP
\fB\-n\fR
Dry run mode. The conversion of svg images will be skipped. In others words,
there is no file operations. The menu will still be printed with all the
icon paths.
.TP
\fB\-s \fIicon_size\fR
Icon size. Default is 24 if not specified.
.TP
\fB\-S\fR
Do not cache svg icons as png images. Recommended for Imlib2 1.8.0 and later.
.TP
\fB\-t \fIterminal\fR
Terminal emulator to use. Default is xterm.
.SH RESOURCES
.TP
.B Desktop Files
The script will go through the .desktop files in the following directories:
$XDG_DATA_DIRS/applications, $XDG_DATA_HOME/applications.
.TP
.B Icon Files
xdg-xmenu will find the icons in the following directories (loosely \
following the method in the freedesktop.org specification):
$XDG_DATA_DIRS/icons, $XDG_DATA_HOME/icons.
.SH Output
.TP
.B Images
Since
.IR xmenu (1)
does not support svg format as icons, this script will convert the found svg
files to png images and cache them in $XDG_CACHE_HOME/xdg-xmenu/.
.TP
.B Menu
The script will output the menu that can be used by
.IR xmenu (1)
to stdout. You can generate a menu with:
.IP
    xdg-menu > menu
.IP
and run xmenu with:
.IP
    xmenu < menu | sh &
.IP
It's not recommended to pipe the output to xmenu due to the speed.
.SH DEPENDENCIES
If you need to convert svg icons to png images, at least one of the
following commands is needed:
.TP
.IR rsvg-convert (1)
This command is provided by librsvg and is the fastest one.
Thus it will be used first if available.
.TP
.IR convert (1)
This command is provided by
.IR ImageMagick (1)
.TP
.IR inkscape (1)
This is about as fast as convert command for small svg icons.
.SH SEE ALSO
.IR xmenu (1),
.SH BUGS
The implementation does not cover everything in the freedesktop specifications,
so it is possible that a desktop entry is parsed incorrectly or an icon is not found.
However in my own experience, it is better than most menu utilities.
.P
Report any bugs at https://github.com/OliverLew/xdg-xmenu/issues
