#!/bin/sh
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
MENU_FILE=$XDG_CACHE_HOME/xdg-xmenu/menu
if [ "$1" = "-u" ]; then
    TERMINAL=st xdg-xmenu > "$MENU_FILE"
elif [ -f "$MENU_FILE" ]; then
    xmenu "$@" < "$MENU_FILE" | sh &
fi
